fix: correct `TypeError: builder.getProjectGraph is not a function`
BREAKING CHANGE: Nx v12.6.x is now the minimum version required to use the plugins

This is due to breaking changes in DevKit's project graph API starting from v12.6.x

Closes #72